### ISSUE TITLE
Inference code

### ISSUE THREAD

**Issue by KHao123** [ercanburak/EVREAL#1]
Hi, thanks for this great work.
Are there any inferece scripts for a custom event data?

Thank you!

**Comment by ercanburak** [comment]
Hi, and thank you for your interest in our work.

The code should work with custom event data as long as the data is in the required "numpy memmap" format. In our [tools](https://github.com/ercanburak/EVREAL/tree/main/tools) folder, we present tools to convert event data in bag or txt format to the numpy format. Then, once the data is in this "numpy memmap" format, you should add a new dataset configuration (in json format) to the [dataset configurations folder](https://github.com/ercanburak/EVREAL/tree/main/config/dataset). In this configuration file, the path of the dataset and the sequences inside it should be described, as in the [example here](https://github.com/ercanburak/EVREAL/blob/main/config/dataset/HQF.json).

I hope this answers your question. By the way, in which format is your dataset?
